name: Deploy Bicep files $(Build.BuildId)

trigger: none

variables:
  location: "eastus"
  templateFile: "Azure Virtual Desktop/main.bicep"
  parametersFile: "Azure Virtual Desktop/main.bicepparam"

pool: Default

stages:
  - stage: preDeploy
    jobs:
      - job: scanWhatif
        displayName: scan and run whatif
        pool: Default

        steps:
          - task: RunARMTTKTests@1
            displayName: Scan Bicep files
            inputs:
              templatelocation: '$(System.DefaultWorkingDirectory)\Azure Virtual Desktop\main.bicep'
              resultLocation: '$(System.DefaultWorkingDirectory)\Azure Virtual Desktop\deploymentresults'
              allTemplatesMain: false
              cliOutputResults: true
              ignoreExitCode: true

          - task: PublishTestResults@2
            displayName: Publish Results
            inputs:
              testResultsFormat: "NUnit"
              testResultsFiles: '$(System.DefaultWorkingDirectory)\Azure Virtual Desktop\deploymentresults\*-armttk.xml'
            condition: always()

          - task: AzureCLI@2
            displayName: Preview Bicep Changes
            inputs:
              azureSubscription: "Azure-labs(9bcdeb1b-b977-4738-b0d7-03e228e47ba4)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az --version
                az deployment sub what-if --location $(location) --template-file $(templateFile) --parameters $(parametersFile)

  - stage: deployBicep
    jobs:
      - job: waitForValidation
        displayName: Wait for external validation
        pool: server
        timeoutInMinutes: 1440 ### job times out in 1 day
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1440 ### task times out in 1 day
            inputs:
              notifyUsers: |
                chrisfelix162@gmail.com
              instructions: "Please validate the build $(Build.BuildId) configuration and resume"
              onTimeout: "resume"

      - job: deployAzure
        displayName: deploy bicep to Azure
        timeoutInMinutes: 1440 ### task times out in 1 day
        pool: Default
        dependsOn: [waitForValidation]

        steps:
          - task: AzureCLI@2
            displayName: Deploy Bicep To Azure
            timeoutInMinutes: 1440 ### task times out in 1 day
            inputs:
              azureSubscription: "Azure-labs(9bcdeb1b-b977-4738-b0d7-03e228e47ba4)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment sub create --location $(location) --template-file $(templateFile) --parameters $(parametersFile)